steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pivot-protocol:$COMMIT_SHA',
      '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pivot-protocol:latest',
      '.'
    ]

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pivot-protocol:$COMMIT_SHA']

  # Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pivot-protocol:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'pivot-protocol',
      '--image', 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pivot-protocol:$COMMIT_SHA',
      '--region', 'us-west1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      # Remove the --port flag to let Cloud Run use its default
      '--memory', '1Gi',
      '--cpu', '1',
      '--max-instances', '10',
      '--min-instances', '0',
      '--timeout', '300',
      '--concurrency', '80',
      '--set-env-vars', 'NODE_ENV=production'
    ]

options:
  machineType: 'E2_HIGHCPU_8'

# Store images in Artifact Registry
images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pivot-protocol:$COMMIT_SHA'
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pivot-protocol:latest'